### ISSUE TITLE
colon character unsupported in columns of table definition

### ISSUE THREAD

**Issue by Xiaoming-lw** [littleK0i/SnowDDL#129]
**Describe the bug**

Snowddl runs error while reading the config yaml files for a table column containing character ":". 

```
snowddl -a *** -r *** -u *** --authenticator=externalbrowser --include-object-types=database,schema,table -c cdb_config_5 plan
2024-10-09 14:58:59.024 - WARNING - [/home/simon/src/snowddl/cdb_config_5/demo_db/run_roman_test/table/test.yaml]: Traceback (most recent call last):
  File "/home/simon/src/.venv/lib/python3.10/site-packages/snowddl/parser/abc_parser.py", line 48, in parse_schema_object_files
    callback(file)
  File "/home/simon/src/.venv/lib/python3.10/site-packages/snowddl/parser/table.py", line 204, in process_table
    name=Ident(col_name),
  File "/home/simon/src/.venv/lib/python3.10/site-packages/snowddl/blueprint/ident.py", line 75, in __init__
    self.name = self._validate_part(name)
  File "/home/simon/src/.venv/lib/python3.10/site-packages/snowddl/blueprint/ident.py", line 47, in _validate_part
    raise ValueError(
ValueError: Character [:] in not allowed in identifier [event_json:useridentity], only ASCII letters, digits and single underscores are accepted
```

Create table:
```
create schema DEMO_DB.RUN_ROMAN_TEST;

create or replace TABLE DEMO_DB.RUN_ROMAN_TEST.TEST (
	"EVENT_JSON:USERIDENTITY" VARIANT
);
```

Convert table into yaml:
```
snowddl-convert -a *** -r *** -u *** --authenticator=externalbrowser --include-object-types=database,schema,table --include-databases=DEMO_DB --ignore-ownership -c cdb_config_5
```
```
columns:
  event_json:useridentity:
    type: VARIANT
```

**Comment by Xiaoming-lw** [comment]
Thank you @littleK0i , it really bring some confusion. I thought it is related with some snowflake feature, but not. Maybe someone just copied it from another query statement and didn't change the name.
