### ISSUE TITLE
Pydantic ValidationError for `NetworkPolicyReference` in account_policy.py

### ISSUE THREAD

**Issue by Github-dm-CDE** [littleK0i/SnowDDL#132]
**Describe the bug**
I am currently trying to update SnowDDL 0.32.0 to 0.33.0. According to the documentation, I have removed the network policy of our account from account_params.yaml and packed it into a separate account_policy.yaml file.

Before:
```yaml
account_params.yaml
---

network_policy: BLOCK_ALL_IPS
```

After:
```yaml
account_policy.yaml
---

network_policy: BLOCK_ALL_IPS
```

After this change I get a ValidationError for `NetworkPolicyReference` in account_policy.py
In the [documentation for the new account_policy file](https://docs.snowddl.com/basic/yaml-configs/account-policy), I could not find any information about the NetworkPolicyReference.

**Expected behavior**
The change should be accepted without a pydantic error message.

**Attach log**
```log
2024-10-14 07:01:44.725 - WARNING - [/builds/customer-data-empowerment/infrastructure-and-deployment/snowddl/config/account_policy.yaml]: Traceback (most recent call last):
  File "/builds/customer-data-empowerment/infrastructure-and-deployment/snowddl/venv/lib[64](https://gitlab.dm-drogeriemarkt.com/customer-data-empowerment/infrastructure-and-deployment/snowddl/-/jobs/44237821#L64)/python3.9/site-packages/snowddl/parser/abc_parser.py", line 38, in parse_single_file
    return callback(file)
  File "/builds/customer-data-empowerment/infrastructure-and-deployment/snowddl/venv/lib64/python3.9/site-packages/snowddl/parser/account_policy.py", line 58, in process_account_policy
    ref = NetworkPolicyReference(
  File "/builds/customer-data-empowerment/infrastructure-and-deployment/snowddl/venv/lib64/python3.9/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for NetworkPolicyReference
object_name
  Field required [type=missing, input_value={'object_type': <ObjectType.ACCOUNT>}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Comment by littleK0i** [comment]
@Github-dm-CDE , should be fixed in `0.34.1`.

Unfortunately, it is a bit difficult to test "account_policy" automatically, since only one ACCOUNT-level policy can exist per account. I'll see if I can create a small test dedicated for ACCOUNT-level policies only to cover this.

**Comment by littleK0i** [comment]
Previously it worked because `NETWORK_POLICY` reference was checked as USER property. And SnowDDL only checked its own users and ignored everyone else.

Now it is the other way around. We check all `POLICY_REFERENCES` for each policy managed by SnowDDL.

**Comment by littleK0i** [comment]
Btw, I see you're using `ACCOUNTADMIN` as role in session. Not recommended and quite dangerous.

But maybe ADMIN users can be brought into config in this case.
