### ISSUE TITLE
Placeholders do not work in yaml identifiers

### ISSUE THREAD

**Issue by JefStat** [littleK0i/SnowDDL#166]
**Describe the bug**
Adding place holder to a identifier results in a yaml parsing error.

**Expected behavior**
Placeholders work to reuse common naming in identifiers

**Attach log**
```
Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/parser/abc_parser.py", line 66, in parse_multi_entity_file
    callback(entity_name, entity_params)
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/parser/warehouse.py", line 81, in process_warehouse
    full_name=AccountObjectIdent(self.env_prefix, warehouse_name),
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/blueprint/ident.py", line 103, in __init__
    self.name = self._validate_part(name)
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/blueprint/ident.py", line 54, in _validate_part
    raise ValueError(
ValueError: Character [{] is not allowed in identifier [${{ project_database_prefix }}_WH], only ASCII letters, digits and single underscores are accepted

Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.8.19/bin/snowddl", line 8, in <module>
    sys.exit(entry_point())
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/app/base.py", line 736, in entry_point
    app = BaseApp()
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/app/base.py", line 44, in __init__
    self.config = self.init_config()
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/app/base.py", line 392, in init_config
    parser.load_blueprints()
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/parser/database.py", line 90, in load_blueprints
    full_name=DatabaseIdent(self.env_prefix, database_name),
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/blueprint/ident.py", line 113, in __init__
    self.database = self._validate_part(database)
  File "/Users//.pyenv/versions/3.8.19/lib/python3.8/site-packages/snowddl/blueprint/ident.py", line 54, in _validate_part
    raise ValueError(
ValueError: Character [.] is not allowed in identifier [.GIT], only ASCII letters, digits and single underscores are accepted
```

**Attach YAML config (if applicable)**
placeholder.yml
```
project_database_prefix: 'INTEGRATIONS'
```
warehouse.yml
```
${{ project_database_prefix }}_WH:
  size: XSMALL
  auto_suspend: 60
  comment: "DEFAULT WAREHOUSE FOR DEVELOPMENT"
```

**Comment by littleK0i** [comment]
Ok, it is an interesting use case. Normally placeholders are applied only for YAML values, but not for keys. If we allow replacements in keys, it means placeholders will be able to potentially override parameter names. May cause some issues down the line.

Before we do anything, did you consider [env_prefix](https://docs.snowddl.com/guides/other-guides/env-prefix) for DEV environments?

**Comment by JefStat** [comment]
I'm planning on using project_database_prefix and env_prefix together. 

I don't have a production running for snowflake as of yet, so not sure what warehouses will be named for now most everything is being named with the project prefix and to prevent spelling mistakes it's an project setting

For more context, I'm trying out snowddl to manage several db object from this dbt script
```
#  add --vars '{mode: deploy}' to execute deployment tasks
on-run-start:
  - "
    {% if var('mode') == 'deploy' %}
      {% do create_database() %}
      {% do create_warehouse() %}
      {% do create_schemas() %}
      {% do create_file_formats() %}
      {% do create_storage_integration() %}
      {% do create_stages() %}
      {% do create_tables() %}
      {% do create_pipes() %}
      {% do grant_privileges() %}
    {% endif %}
```

Most of these macros have the following where target.name is the DEV or PROD env_prefix
```
    CREATE DATABASE IF NOT EXISTS {{ var('project_database_prefix') }}_{{ target.name }};
```

**Comment by littleK0i** [comment]
Env prefix can be composite, e.g. `DEV_INTEGRATION`.

Object names for schema objects will be: `DEV_INTEGRATION__<DB>.<SCHEMA>.<TABLE>`.
Warehouse names will be: `DEV_INTEGRATION__<NAME>`.

Alternatively, since it is basic YAML, you may use `integrations` as name for now and replace it later with basic mass-replace. Fundamentally, it should lead to config which is significantly easier to read and search. Especially if you have some other code referring to real names without using placeholders, like Python or some reporting tools.

**Comment by littleK0i** [comment]
@JefStat , did you manage to resolve this issue one way or another?

My current intention is to close this ticket. I did some tests related to possibility of using of placeholders in config keys. And currently I am leaning against this idea.

The main reasons are:
1. It may create some very confusing setups when combined with wildcard pattern matching.
2. Schema object names come from YAML file names. In order to support this feature fully, we will have to allow placeholders in file names as well, e.g. `my_table_${{ foo }}.yaml`.
3. Syntax highlight may go haywire.

Dynamic naming is still possible via [programmatic config](https://docs.snowddl.com/advanced/programmatic-config). A bit more difficult, but it should cover all future use-cases.

**Comment by JefStat** [comment]
I created a bash script that would load a different placeholder file path based on which prefix was used as an argument.
So instead of of a placeholder name with a prefix 
Eg: {dev_storage_intergation}
I have a placeholder filename with a prefix
Eg: dev_placeholders.yml

**Comment by littleK0i** [comment]
Yes, this is a good solution.

You may specify path to placeholder file directly using CLI option: `--placeholder-path`

I'll close this issue for now.
